# -*- coding: utf-8 -*-
"""07_food_vision_milestone_project_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G3D42hXIHY2pfxh3LAIuHcKapb6cz98c

## Milestone Project 1 : Food Vision Big

### Check GPU

Google Colab offers free GPUs (thank you google), however, not all of them are compatible with mixed precision training.PendingDeprecationWarning.

Google Colab offers: 
* K80(not compatible)
* P100 (not compatible)
* Tesla T4 (compatible)

Knowing this, in order to use mixed precison training we need access to a Tesla T4(from within Google Colab) or if we're using our own hardware, our GPU needs a score of 7.0+ (see here: https://developer.nvidia.com/cuda-gpus)
"""

!nvidia-smi -L

