# -*- coding: utf-8 -*-
"""08_introduction_to_nlp_in_tensorflow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Chx_UraOYKH3saYq4BVxnh66Ih4SarB_

# Introduction to NLP Fundamentals in TensorFlow 

NLP has the goal of deriving information out of natural language (could be seqences text or speech).

Another common for NLP programs is sequence to sequence problems(seq2seq).

# Check for GPU
"""

!nvidia-smi -L

"""# Get helper function """

!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

# Import series of helper functions for the notebook

from helper_functions import unzip_data,create_tensorboard_callback,plot_loss_curves,compare_historys

"""## Get a tex dataset 

the dataset we're goinig to be using is Kaggle's introduction to NLP dataset (text samples of Tweets labelled as disaster or not disaster).

see the original source here: https://www.kaggle.com/c/nlp-getting-started/
"""

!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

# unzip data 
unzip_data("nlp_getting_started.zip")

"""## visualizing a text dataset 

To visualize our text samples, we first have to read them in, one way to do so would be to use Python: https://realpython.com/read-write-files-python/

But I prefer to get visual straight away.
So another way to do this is to use pandas...
"""

import pandas as pd
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
train_df.head()

train_df["text"][1]

# shuffle training dataframe